"""Evidence based optimization for durable Botpipe workflows.

The optimizer deliberately works from journaled operations. A Python workflow's
source manifest says what may run; it is never treated as proof that a path ran.
"""

from .candidates import (
    CandidateEvaluationReport,
    CandidateFile,
    CandidateManifest,
    CandidateWorkspace,
    CommandResult,
    candidate_manifest,
    evaluate_candidate_workspace,
    prepare_candidate_workspace,
    repository_root_for,
    validate_authoritative_sources_unchanged,
)
from .evaluations import (
    CaseKind,
    ValidatedEvalCase,
    ValidatedEvalManifest,
    validate_eval_case_manifest,
    validate_workflow_parameters,
)
from .evidence import (
    EvidenceSnapshot,
    Objective,
    Observation,
    StepMetric,
    StepRanking,
    baseline_surface_id,
    capture_evidence_snapshot,
)
from .optimization import (
    OperationMetrics,
    OperationObservation,
    OptimizationCandidate,
    OptimizationReport,
    ProviderDispatchObservation,
    RunObservation,
    SourceManifest,
    SourceSite,
    build_operation_metrics,
    capture_source_manifest,
    load_run_observation,
    optimize_observations,
    rank_optimization_candidates,
    validate_optimization_candidate,
    validate_optimization_report,
    write_optimization_report,
)
from .parameters import (
    PortfolioReviewParameters,
    SelectedWorkflowTaskFramingParameters,
    SelectedWorkflowTaskFramingWithEvidenceParameters,
    TaskContextParameters,
    TaskFramingParameters,
    TaskFramingWithEvidenceParameters,
)
from .recommendations import (
    OptimizationCandidateSelection,
    build_empty_candidate_set,
    finalize_candidate_review_payload,
    finalize_candidate_set_payload,
    load_optimization_candidate,
    publish_recommendation,
    read_candidate_review,
    read_candidate_set,
    read_publication_receipt,
    read_refinement_handoff,
    select_handoff_candidate,
    validate_candidate_review,
    validate_candidate_set,
)
from .records import (
    CandidateReview,
    CandidateSet,
    PublicationReceipt,
    RefinementHandoff,
)

__all__ = [
    "CandidateEvaluationReport",
    "CandidateFile",
    "CandidateManifest",
    "CandidateReview",
    "CandidateSet",
    "CandidateWorkspace",
    "CaseKind",
    "CommandResult",
    "EvidenceSnapshot",
    "Objective",
    "Observation",
    "OperationMetrics",
    "OperationObservation",
    "OptimizationCandidate",
    "OptimizationCandidateSelection",
    "OptimizationReport",
    "PortfolioReviewParameters",
    "ProviderDispatchObservation",
    "PublicationReceipt",
    "RefinementHandoff",
    "RunObservation",
    "SelectedWorkflowTaskFramingParameters",
    "SelectedWorkflowTaskFramingWithEvidenceParameters",
    "SourceManifest",
    "SourceSite",
    "StepMetric",
    "StepRanking",
    "TaskContextParameters",
    "TaskFramingParameters",
    "TaskFramingWithEvidenceParameters",
    "ValidatedEvalCase",
    "ValidatedEvalManifest",
    "baseline_surface_id",
    "build_empty_candidate_set",
    "build_operation_metrics",
    "candidate_manifest",
    "capture_evidence_snapshot",
    "capture_source_manifest",
    "evaluate_candidate_workspace",
    "finalize_candidate_review_payload",
    "finalize_candidate_set_payload",
    "load_optimization_candidate",
    "load_run_observation",
    "optimize_observations",
    "prepare_candidate_workspace",
    "publish_recommendation",
    "rank_optimization_candidates",
    "read_candidate_review",
    "read_candidate_set",
    "read_publication_receipt",
    "read_refinement_handoff",
    "repository_root_for",
    "select_handoff_candidate",
    "validate_authoritative_sources_unchanged",
    "validate_candidate_review",
    "validate_candidate_set",
    "validate_eval_case_manifest",
    "validate_optimization_candidate",
    "validate_optimization_report",
    "validate_workflow_parameters",
    "write_optimization_report",
]
