from tests.unit.test_stdlib_and_extensions import (
    test_candidate_surface_helpers_allow_canonical_relative_paths_with_repo_local_sources,
    test_candidate_surface_helpers_materialize_baseline_and_derive_candidate_diff,
    test_candidate_surface_helpers_normalize_overlay_results_for_single_and_multi_workflow_receipts,
    test_candidate_surface_helpers_normalize_repo_boundary_and_stay_reexported_from_stdlib,
    test_candidate_surface_helpers_reject_authoritative_source_drift,
    test_candidate_surface_helpers_reject_non_repo_relative_authoritative_drift_paths,
    test_candidate_surface_helpers_reject_non_repo_relative_baseline_paths,
    test_candidate_surface_helpers_reject_non_repo_relative_overlay_paths,
    test_candidate_surface_helpers_validate_baseline_manifest_checks_boundary_and_digest,
    test_candidate_surface_helpers_validate_candidate_manifest_checks_boundary_and_digest,
    test_candidate_surface_helpers_validate_overlay_normalizes_pytest_and_falls_back_to_importable_package_root,
)
