"""Generic workflow authoring helpers shared across active workflow packages."""

from .composition import adopt_child_artifacts, require_child_workflow_result, run_child_workflow
from .control import await_input_on_outcome_tags, event_on_outcome_tags, global_routes, merge_transitions
from .json_artifacts import JsonArtifactSpec
from .lifecycle import (
    open_workflow_sessions,
    write_invocation_contract,
    write_publication_receipt,
    write_workflow_json,
)
from .prompts import PromptBundle, PromptPair
from .validation import (
    contains_hidden_execution_signal,
    deduped_string_list_fields,
    extract_workflow_names_from_capability_snapshot,
    extract_workflow_names_from_portfolio_health,
    require_existing_artifact_paths,
    ValidationIssue,
    ValidationReport,
    normalize_optional_string,
    normalize_unique_strings,
    optional_text_fields,
    positive_int_fields,
    read_json_object,
    read_model_file,
    require_mapping,
    require_mapping_list,
    require_non_negative_int,
    require_non_empty_string,
    require_positive_int,
    require_true_flag,
    read_required_text,
    required_text_fields,
    validate_selected_workflow_artifact_alignment,
    validate_selected_workflow_capability_and_authoring_snapshots,
    require_string_list,
    require_unique_values,
    validate_authoritative_artifact_subset,
    validate_no_hidden_execution_signal,
    validate_publication_boundary,
    validate_selected_workflow_authoring_surface_snapshot,
    validate_selected_workflow_capability_snapshot,
    validate_selected_workflow_decomposition_surface_snapshot,
    validate_selected_workflow_name_alignment,
    validate_model_file,
    write_model_file,
)

__all__ = [
    "PromptBundle",
    "PromptPair",
    "JsonArtifactSpec",
    "ValidationIssue",
    "ValidationReport",
    "contains_hidden_execution_signal",
    "deduped_string_list_fields",
    "extract_workflow_names_from_capability_snapshot",
    "extract_workflow_names_from_portfolio_health",
    "normalize_optional_string",
    "normalize_unique_strings",
    "optional_text_fields",
    "adopt_child_artifacts",
    "await_input_on_outcome_tags",
    "event_on_outcome_tags",
    "global_routes",
    "merge_transitions",
    "open_workflow_sessions",
    "read_json_object",
    "read_required_text",
    "read_model_file",
    "require_existing_artifact_paths",
    "require_child_workflow_result",
    "require_mapping",
    "require_mapping_list",
    "require_non_negative_int",
    "require_non_empty_string",
    "require_positive_int",
    "require_true_flag",
    "positive_int_fields",
    "required_text_fields",
    "require_string_list",
    "require_unique_values",
    "run_child_workflow",
    "validate_selected_workflow_artifact_alignment",
    "validate_authoritative_artifact_subset",
    "validate_selected_workflow_capability_and_authoring_snapshots",
    "validate_selected_workflow_authoring_surface_snapshot",
    "validate_no_hidden_execution_signal",
    "validate_model_file",
    "validate_publication_boundary",
    "validate_selected_workflow_capability_snapshot",
    "validate_selected_workflow_decomposition_surface_snapshot",
    "validate_selected_workflow_name_alignment",
    "write_model_file",
    "write_invocation_contract",
    "write_publication_receipt",
    "write_workflow_json",
]
